"""llms.txt generator and validator.

Generates and validates llms.txt and llms-full.txt files
following the llmstxt.org specification.

These files help AI models understand your site and cite it correctly.

Usage:
    searchstack llms generate          # generate llms.txt + llms-full.txt
    searchstack llms validate          # validate existing files
    searchstack llms check             # check if your site has llms.txt
"""

from __future__ import annotations

import json
import re
import urllib.request
import urllib.error
from datetime import datetime
from pathlib import Path

from searchstack.config import Config
from searchstack import snapshots


def _fetch(url: str, timeout: int = 10) -> str | None:
    """Fetch URL content, return None on error."""
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0 SearchStack/1.0"})
        return urllib.request.urlopen(req, timeout=timeout).read().decode("utf-8", errors="ignore")
    except Exception:
        return None


def _extract_meta(html: str) -> dict:
    """Extract title, description, h1, h2s from HTML."""
    title_m = re.search(r"<title[^>]*>(.*?)</title>", html, re.DOTALL)
    title = title_m.group(1).strip() if title_m else ""

    desc_m = re.search(r'<meta\s+name=["\']description["\']\s+content=["\']([^"\']*)', html, re.IGNORECASE)
    desc = desc_m.group(1).strip() if desc_m else ""

    h1_m = re.search(r"<h1[^>]*>(.*?)</h1>", html, re.DOTALL | re.IGNORECASE)
    h1 = re.sub(r"<[^>]+>", "", h1_m.group(1)).strip() if h1_m else ""

    h2s = re.findall(r"<h2[^>]*>(.*?)</h2>", html, re.DOTALL | re.IGNORECASE)
    h2_texts = [re.sub(r"<[^>]+>", "", h).strip() for h in h2s if h.strip()]

    # Word count (rough)
    text = re.sub(r"<script[^>]*>.*?</script>", "", html, flags=re.DOTALL)
    text = re.sub(r"<style[^>]*>.*?</style>", "", text, flags=re.DOTALL)
    text = re.sub(r"<[^>]+>", " ", text)
    words = len(text.split())

    return {"title": title, "description": desc, "h1": h1, "h2s": h2_texts, "words": words}


def _get_sitemap_urls(config: Config) -> list[str]:
    """Fetch and parse sitemap URLs."""
    sitemap_url = config.sitemap or f"https://{config.domain}/sitemap.xml"
    content = _fetch(sitemap_url)
    if not content:
        return []
    urls = re.findall(r"<loc>(https?://[^<]+)</loc>", content)
    return [u for u in urls if not u.endswith((".xml", ".txt", ".md"))]


def _generate_llms_txt(config: Config, pages: list[dict]) -> str:
    """Generate llms.txt (short version) following llmstxt.org spec."""
    domain = config.domain
    lines = []

    lines.append(f"# {domain}")
    lines.append("")

    # Find homepage description
    home = next((p for p in pages if p["path"] == "/" or p["path"] == ""), None)
    if home and home["description"]:
        lines.append(f"> {home['description']}")
        lines.append("")

    # Group pages by section
    sections: dict[str, list[dict]] = {}
    for page in pages:
        path = page["path"]
        if path == "/" or path == "":
            continue

        # Determine section from URL structure
        parts = path.strip("/").split("/")
        if len(parts) >= 2:
            section = parts[0].replace("-", " ").title()
        elif path.strip("/") in ("about", "pricing", "product", "features", "contact"):
            section = "Main"
        else:
            section = "Pages"

        sections.setdefault(section, []).append(page)

    # Output sections
    for section_name, section_pages in sections.items():
        lines.append(f"## {section_name}")
        lines.append("")
        for page in section_pages:
            title = page["title"] or page["h1"] or page["path"]
            url = f"https://{domain}{page['path']}"
            desc = page["description"]
            if desc:
                lines.append(f"- [{title}]({url}): {desc}")
            else:
                lines.append(f"- [{title}]({url})")
        lines.append("")

    return "\n".join(lines)


def _generate_llms_full_txt(config: Config, pages: list[dict]) -> str:
    """Generate llms-full.txt (detailed version) with page summaries."""
    domain = config.domain
    lines = []

    lines.append(f"# {domain} — Full Reference")
    lines.append("")
    lines.append(f"> Complete site content for AI model reference.")
    lines.append(f"> Generated by searchstack on {datetime.now().strftime('%Y-%m-%d')}")
    lines.append("")

    for page in pages:
        title = page["title"] or page["h1"] or page["path"]
        url = f"https://{domain}{page['path']}"

        lines.append(f"## {title}")
        lines.append("")
        lines.append(f"URL: {url}")
        if page["description"]:
            lines.append(f"Description: {page['description']}")
        lines.append(f"Word count: ~{page['words']}")
        lines.append("")

        if page["h1"] and page["h1"] != title:
            lines.append(f"# {page['h1']}")
            lines.append("")

        if page["h2s"]:
            lines.append("Sections:")
            for h2 in page["h2s"]:
                lines.append(f"- {h2}")
            lines.append("")

        lines.append("---")
        lines.append("")

    return "\n".join(lines)


def _validate_llms_txt(content: str, domain: str) -> list[dict]:
    """Validate llms.txt content against spec. Returns list of issues."""
    issues = []

    if not content:
        issues.append({"level": "error", "msg": "File is empty"})
        return issues

    lines = content.strip().split("\n")

    # Must start with # Title
    if not lines or not lines[0].startswith("# "):
        issues.append({"level": "error", "msg": "Must start with '# Site Name' heading"})

    # Should have a blockquote description
    has_blockquote = any(line.startswith("> ") for line in lines)
    if not has_blockquote:
        issues.append({"level": "warning", "msg": "Missing '> description' blockquote after title"})

    # Should have at least one ## section
    sections = [line for line in lines if line.startswith("## ")]
    if not sections:
        issues.append({"level": "warning", "msg": "No '## Section' headings found"})

    # Should have links
    links = re.findall(r'\[([^\]]+)\]\(([^)]+)\)', content)
    if not links:
        issues.append({"level": "error", "msg": "No markdown links found — file should contain [Title](URL) links"})

    # Check that links point to the right domain
    for title, url in links:
        if domain not in url and not url.startswith("/"):
            issues.append({"level": "warning", "msg": f"Link points to external domain: {url}"})

    # Check file size
    size = len(content)
    if size < 100:
        issues.append({"level": "warning", "msg": f"Very short ({size} bytes) — consider adding more detail"})
    if size > 50000:
        issues.append({"level": "warning", "msg": f"Very large ({size} bytes) — this is llms.txt, not llms-full.txt"})

    # Check for descriptions after links
    links_with_desc = re.findall(r'\[([^\]]+)\]\([^)]+\):\s+\S', content)
    links_without = len(links) - len(links_with_desc)
    if links_without > len(links) * 0.5:
        issues.append({"level": "info", "msg": f"{links_without}/{len(links)} links have no description — adding ': description' helps AI models"})

    return issues


def cmd_generate(config: Config) -> None:
    """Generate llms.txt and llms-full.txt from sitemap."""
    if not config.domain:
        print("  No domain configured. Set 'domain' in .searchstack.toml")
        return

    print(f"  Generating llms.txt for {config.domain}...\n")

    urls = _get_sitemap_urls(config)
    if not urls:
        print("  Could not fetch sitemap URLs")
        return

    print(f"  Crawling {len(urls)} pages...")

    pages = []
    for i, url in enumerate(urls, 1):
        path = url.replace(f"https://{config.domain}", "").replace(f"http://{config.domain}", "") or "/"
        html = _fetch(url)
        if html:
            meta = _extract_meta(html)
            meta["path"] = path
            meta["url"] = url
            pages.append(meta)
            status = "ok"
        else:
            pages.append({"path": path, "url": url, "title": "", "description": "", "h1": "", "h2s": [], "words": 0})
            status = "failed"

        if i % 5 == 0 or i == len(urls):
            print(f"    [{i}/{len(urls)}] crawled")

    # Generate files
    llms_txt = _generate_llms_txt(config, pages)
    llms_full = _generate_llms_full_txt(config, pages)

    # Save
    output_dir = Path.cwd()
    llms_path = output_dir / "llms.txt"
    llms_full_path = output_dir / "llms-full.txt"

    with open(llms_path, "w") as f:
        f.write(llms_txt)
    with open(llms_full_path, "w") as f:
        f.write(llms_full)

    print(f"\n  Generated:")
    print(f"    {llms_path} ({len(llms_txt)} bytes, {len(llms_txt.splitlines())} lines)")
    print(f"    {llms_full_path} ({len(llms_full)} bytes, {len(llms_full.splitlines())} lines)")
    print(f"\n  Pages processed: {len(pages)}")
    print(f"  Sections: {len(set(p['path'].strip('/').split('/')[0] for p in pages if '/' in p['path'].strip('/')))}")

    print(f"\n  Next steps:")
    print(f"    1. Review and edit the generated files")
    print(f"    2. Host at https://{config.domain}/llms.txt")
    print(f"    3. Host at https://{config.domain}/llms-full.txt")
    print(f"    4. Add to robots.txt or sitemap")
    print(f"    5. Run 'searchstack llms validate' to check")


def cmd_validate(config: Config) -> None:
    """Validate llms.txt and llms-full.txt on the live site."""
    domain = config.domain
    if not domain:
        print("  No domain configured. Set 'domain' in .searchstack.toml")
        return

    print(f"  Validating llms.txt for {domain}...\n")

    for filename in ["llms.txt", "llms-full.txt"]:
        url = f"https://{domain}/{filename}"
        print(f"  {filename}:")

        content = _fetch(url)
        if content is None:
            print(f"    NOT FOUND at {url}")
            print(f"    Generate with: searchstack llms generate")
            print()
            continue

        print(f"    Found: {len(content)} bytes, {len(content.splitlines())} lines")

        issues = _validate_llms_txt(content, domain)

        if not issues:
            print(f"    All checks passed")
        else:
            for issue in issues:
                icon = {"error": "X", "warning": "!", "info": "i"}.get(issue["level"], "?")
                print(f"    [{icon}] {issue['msg']}")

        # Count links
        links = re.findall(r'\[([^\]]+)\]\(([^)]+)\)', content)
        print(f"    Links: {len(links)}")

        # Count sections
        sections = [line for line in content.split("\n") if line.startswith("## ")]
        print(f"    Sections: {len(sections)}")

        print()

    # Check robots.txt for llms.txt reference
    robots = _fetch(f"https://{domain}/robots.txt")
    if robots and "llms.txt" in robots:
        print(f"  robots.txt: mentions llms.txt")
    elif robots:
        print(f"  robots.txt: does NOT mention llms.txt")
        print(f"    Consider adding: Sitemap: https://{domain}/llms.txt")
    else:
        print(f"  robots.txt: not found")


def cmd_check(config: Config) -> None:
    """Quick check: does the site have llms.txt?"""
    domain = config.domain
    if not domain:
        print("  No domain configured")
        return

    print(f"  Checking {domain} for AI-ready files...\n")

    files_to_check = [
        ("llms.txt", "LLM site description (llmstxt.org spec)"),
        ("llms-full.txt", "LLM detailed reference"),
        ("robots.txt", "Crawler directives"),
        ("sitemap.xml", "Page index for crawlers"),
        (".well-known/ai-plugin.json", "OpenAI plugin manifest"),
    ]

    for filename, description in files_to_check:
        url = f"https://{domain}/{filename}"
        try:
            req = urllib.request.Request(url, method="HEAD", headers={"User-Agent": "Mozilla/5.0 SearchStack/1.0"})
            resp = urllib.request.urlopen(req, timeout=5)
            size = resp.headers.get("Content-Length", "?")
            print(f"    {filename:<35} FOUND  ({size} bytes) — {description}")
        except urllib.error.HTTPError as e:
            if e.code == 404:
                print(f"    {filename:<35} MISSING — {description}")
            else:
                print(f"    {filename:<35} ERROR {e.code}")
        except Exception:
            print(f"    {filename:<35} ERROR")

    # Check if sitemap references llms files
    sitemap = _fetch(f"https://{domain}/sitemap.xml")
    if sitemap:
        has_llms = "llms.txt" in sitemap or "llms-full.txt" in sitemap
        if has_llms:
            print(f"\n  sitemap.xml references llms files")
        else:
            print(f"\n  sitemap.xml does NOT reference llms files")
            print(f"  Consider adding llms.txt and llms-full.txt to your sitemap")


def run(config: Config, *args: str) -> None:
    """llms.txt generator and validator.

    Usage:
        searchstack llms generate    Generate llms.txt + llms-full.txt from sitemap
        searchstack llms validate    Validate existing files on live site
        searchstack llms check       Quick check: does site have AI-ready files?
    """
    subcmd = args[0] if args else "check"

    if subcmd == "generate":
        cmd_generate(config)
    elif subcmd == "validate":
        cmd_validate(config)
    elif subcmd == "check":
        cmd_check(config)
    else:
        print(f"  Unknown subcommand: {subcmd}")
        print(f"  Available: generate, validate, check")
